name: PR Build Validation

on:
  pull_request:
    branches:
      - ACC
      - master

  workflow_dispatch:
    inputs:
      apps:
        type: string
        required: false
        description: The apps for which to run the regression test

      test_types:
        type: string
        required: false
        description: The types of tests to run (analysis, user_mutation_log, role_mutation_log)

jobs:
  regression-tests:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Find differences
        id: find-differences
        shell: powershell
        run: |
          python -u find_differences.py
          $has_differences = $LASTEXITCODE -eq 1
          echo "::set-output name=has_differences::$has_differences"


      - name: Generate regression test summary
        continue-on-error: true
        if: ${{ always() && steps.find-differences.outputs.has_differences == 'True' }}
        run: |
          echo "find differences has differences"

