name: PR Build Validation

on:
  pull_request:
    branches:
      - ACC
      - master

  workflow_dispatch:
    inputs:
      apps:
        type: string
        required: false
        description: The apps for which to run the regression test

      test_types:
        type: string
        required: false
        description: The types of tests to run (analysis, user_mutation_log, role_mutation_log)

jobs:
  regression-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Find differences
        id: find-differences
        run: |
          python -u find_differences.py


